import { v4 as uuidv4 } from 'uuid';
import type { Product, Category } from '@/types';

export const sampleCategories: Category[] = [
  {
    id: uuidv4(),
    name: 'Electronics',
    slug: 'electronics',
    description: 'Latest gadgets and electronic devices',
  },
  {
    id: uuidv4(),
    name: 'Clothing',
    slug: 'clothing',
    description: 'Fashion and apparel for all occasions',
  },
  {
    id: uuidv4(),
    name: 'Home & Garden',
    slug: 'home-garden',
    description: 'Everything for your home and garden',
  },
  {
    id: uuidv4(),
    name: 'Books',
    slug: 'books',
    description: 'Physical and digital books',
  },
];

export const sampleProducts: Product[] = [
  {
    id: uuidv4(),
    name: 'Wireless Headphones Pro',
    slug: 'wireless-headphones-pro',
    description: 'Premium wireless headphones with active noise cancellation, 30-hour battery life, and superior sound quality. Perfect for music lovers and professionals.',
    price: 2499,
    stock: 25,
    categoryId: sampleCategories[0].id,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Premium Cotton T-Shirt',
    slug: 'premium-cotton-t-shirt',
    description: '100% organic cotton t-shirt with a comfortable fit. Available in multiple colors. Soft, breathable, and perfect for everyday wear.',
    price: 599,
    stock: 100,
    categoryId: sampleCategories[1].id,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Garden Tool Set Deluxe',
    slug: 'garden-tool-set-deluxe',
    description: 'Complete garden tool set including trowel, cultivator, transplanter, weeder, and pruning shears. High-quality stainless steel with ergonomic handles.',
    price: 1299,
    stock: 15,
    categoryId: sampleCategories[2].id,
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Bestseller Fiction Novel',
    slug: 'bestseller-fiction-novel',
    description: 'A gripping tale of mystery and adventure that will keep you on the edge of your seat. Over 1 million copies sold worldwide.',
    price: 399,
    stock: 50,
    categoryId: sampleCategories[3].id,
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Smart Watch Series 5',
    slug: 'smart-watch-series-5',
    description: 'Advanced fitness tracking, heart rate monitoring, GPS, and smartphone integration. Water-resistant up to 50 meters. Battery lasts up to 7 days.',
    price: 4999,
    stock: 10,
    categoryId: sampleCategories[0].id,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Denim Jacket Classic',
    slug: 'denim-jacket-classic',
    description: 'Timeless denim jacket with a vintage wash. Durable construction with brass buttons and multiple pockets. A wardrobe essential.',
    price: 1899,
    stock: 30,
    categoryId: sampleCategories[1].id,
    image: 'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=800&q=80',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
